# TWO FUNCTIONS

# Function 1-   retrieve an svg file which has alrady had relativeToAbsolute run on it
#               and split it into a series of beginning + end points, with a reference to
#               the original line in full

# Function 2-   add together the distance of a path, generated by a seperate pathfinding function

# OBVIOUS QUESTION:
# given were pathfinding with lines rather than points, which is preferable?
# opt 1. when checking paths, flip every line individually to find fastest version of that path
# opt 2. when calculating paths, have flipping the line as an option
# i lean towards option 2 because option 1 seems very computationally expensive, but we will see when
# we get there

print(":D")